stdLogLevel: debug

defaultCron:
  hour: 18
  minute: 0

apiToken: ceeded729d8c61a44331ed8c7402e354

mq:
  connection:
    host: 127.0.0.1
  exchange:
    name: sse
    options:
      durable: true
      autoDelete: true
  queue:
    name: mail
    options:
      durable: true
      autoDelete: true